version: '3.3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3333:3333
    restart: on-failure
    depends_on:
      - mongodb
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  database:
